version: '3.2'

services:
  pausegarra:
    container_name: pausegarra
    image: psegarra/pausegarra:${VERSION}
    ports:
      - "3035:80"
    restart: always
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: '0.1'
        reservations:
          memory: 50M
          cpus: '0.1'